### ISSUE TITLE
Not possible to have a delayed init as on version 5.x

### ISSUE THREAD

**Issue by rkardo58** [apptentive/apptentive-kit-android#13]
Hi,

I need to have the init customizable and defined by an API setting, and right now when I don't register the app just crashes or it doesn't load the views as it should. 

Apptentive.INSTANCE.isRegistered does not work to prevent it.

java.lang.NoClassDefFoundError: apptentive.com.android.util.Log
                                                                                              	at apptentive.com.android.util.Log.d(Unknown Source:0)
                                                                                              	at apptentive.com.android.feedback.ApptentiveNullClient.getUnreadMessageCount(ApptentiveClient.kt:77)
                                                                                              	at apptentive.com.android.feedback.Apptentive.getUnreadMessageCount(Apptentive.kt:520)
                                                                                              	at com.smithmicro.safepath.family.core.analytics.apptentive.ApptentiveRatingEngine.getUnreadMessageCount(ApptentiveRatingEngine.java:132)

**Comment by rkardo58** [comment]
Your logger only gets initialized after registering. So you try to log if not registered and it crashes because there's no logger.
I have to check before all methods if its registered.

**Comment by ChaseApptentive** [comment]
@rkardo58 

Yes, that's how it's currently intended to work. Apptentive needs to be registered in order for any other part of the SDK to work, including the logger.

But this is an area where we can do better, and we'll work on improving this in the near future.

In the meantime, something you can do to check if the SDK is registered is to use the register callback method shown [here](https://learn.apptentive.com/knowledge-base/android-integration-guide/#registering-unregistering-the-activity-callback-to-the-sdk:~:text=style/YourTheme%22%3E-,Using%20Registration%20Callbacks,-Our%20registration%20callbacks). 

Also, if you can provide some more info (maybe code snippets) of how you're doing the "init customizable and defined by an API setting" part of your code, we could try to repro this same scenario on our end.

Thanks.
